
openapi: 3.0.1
info:
  title: Question Generator
  description:  |
    ## Generate question from text.
    ---
    How to use:
      * Typing text
      * Excute and wait until the result shows up
    ---
    You can also experiences Question Generator in
    [Webpage](https://qg-wook-2.endpoint.ainize.ai/)
  version: 1.0.0
  license:
    name: "MIT"
    url: ""
servers:
  - url: 'https://qg-wook-2.endpoint.ainize.ai'

paths:
  /generate:
    post:
      tags:
      - Question Generator
      requestBody:
        required: true
        description: "Type text"
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                input:
                  description: Type text
                  type: string

            encoding:
              files:
                contentType: string
      responses:
         '200':
            description: success
            content:
              application/json:
                  schema:
                    type: object
                    additionalProperties:
                      type: string

         '400':
            description: Bad request (Can not load images)
         '500':
            description: Server Side Error
  /answer:
    post:
      tags:
      - Question Generator
      requestBody:
        required: true
        description: "Type text"
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                input:
                  description: Type text
                  type: string

            encoding:
              files:
                contentType: string
      responses:
         '200':
            description: success
            content:
              application/json:
                  schema:
                    type: object
                    additionalProperties:
                      type: string

         '400':
            description: Bad request (Can not load images)
         '500':
            description: Server Side Error
